"""AI-CONTEXT structured explanation output.

D4-D6: structured JSON output, operator review summary, and UI handoff.
Read-only sidecar layer. No score mutation. No trading instruction.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ai_context.contracts.explanation_contract import READ_ONLY_SAFETY
from ai_context.contracts.explanation_contract import build_ai_context_report


OUTPUT_CONTRACT_VERSION = "AI_CONTEXT_OUTPUT_V1"


def _require_report(report: dict[str, Any]) -> dict[str, Any]:
    if not isinstance(report, dict):
        raise ValueError("report must be a dict")
    if report.get("app") != "AI-CONTEXT":
        raise ValueError("report.app must be AI-CONTEXT")
    return report


def build_structured_explanation_output(stock_app_contract: dict[str, Any]) -> dict[str, Any]:
    report = build_ai_context_report(stock_app_contract)
    candidates = report.get("candidate_explanations", [])

    return {
        "app": "AI-CONTEXT",
        "contract_version": OUTPUT_CONTRACT_VERSION,
        "source_report_contract_version": report.get("contract_version"),
        "market": report.get("market"),
        "trade_date": report.get("trade_date"),
        "input_manifest_id": report.get("input_manifest_id"),
        "candidate_count": len(candidates),
        "explanations": candidates,
        "mutation_guard": report.get("mutation_guard"),
        "operator_review_summary": report.get("operator_review_summary"),
        "json_schema_note": "Structured sidecar output for UI/workflow review only.",
        **READ_ONLY_SAFETY,
    }


def build_operator_review_summary(structured_output: dict[str, Any]) -> dict[str, Any]:
    _require_report({"app": "AI-CONTEXT", **structured_output})
    explanations = structured_output.get("explanations", [])

    high = [item for item in explanations if item.get("potential_level") == "HIGH_POTENTIAL"]
    limited = [item for item in explanations if item.get("data_quality_state") == "PASS_LIMITED"]
    risks = sum(len(item.get("risk_flags", [])) for item in explanations)

    return {
        "app": "AI-CONTEXT",
        "summary_type": "operator_review_summary",
        "candidate_count": len(explanations),
        "high_potential_count": len(high),
        "pass_limited_count": len(limited),
        "risk_flag_count": risks,
        "operator_review_required": True,
        "review_required_reasons": [
            "AI-CONTEXT is explanation-only.",
            "Scores are generated by deterministic sidecar rules.",
            "Risk flags must remain visible to the operator.",
            "No buy or sell instruction is allowed.",
        ],
        "allowed_next_step": "ui_app_read_only_workflow_review",
        "blocked_next_steps": [
            "real_trade_execution",
            "brokerage_order_submission",
            "exchange_api_order_submission",
            "auto_buy_sell_recommendation",
        ],
        **READ_ONLY_SAFETY,
    }


def build_ui_workflow_handoff(structured_output: dict[str, Any]) -> dict[str, Any]:
    review_summary = build_operator_review_summary(structured_output)
    return {
        "app": "AI-CONTEXT",
        "handoff": "ui_app_read_only_workflow",
        "handoff_ready": True,
        "target": "UI-APP-1",
        "payload": {
            "structured_output": structured_output,
            "operator_review_summary": review_summary,
        },
        "ui_allowed_actions": [
            "view_ranked_watchlist_explanations",
            "view_score_breakdown",
            "view_reason_codes",
            "view_risk_flags",
            "mark_for_manual_review",
        ],
        "ui_forbidden_actions": [
            "buy",
            "sell",
            "place_order",
            "connect_brokerage",
            "connect_exchange_api",
            "store_api_key",
        ],
        **READ_ONLY_SAFETY,
    }


def write_ai_context_output(stock_app_contract: dict[str, Any], output_path: str | Path) -> dict[str, Any]:
    structured_output = build_structured_explanation_output(stock_app_contract)
    review_summary = build_operator_review_summary(structured_output)
    handoff = build_ui_workflow_handoff(structured_output)

    payload = {
        "structured_output": structured_output,
        "operator_review_summary": review_summary,
        "ui_workflow_handoff": handoff,
        **READ_ONLY_SAFETY,
    }

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")

    return {
        "ok": True,
        "output_path": str(path),
        "payload": payload,
        **READ_ONLY_SAFETY,
    }
