from __future__ import annotations

from apps.v2_r1_factor_contract_foundation_app_1 import (
    ChampionChallengerStatus,
    FactorDefinition,
    FactorLifecycle,
    ForecastTargetDefinition,
    ForecastTargetType,
    TargetBasis,
    ValidationStatus,
    build_state_sync_anchor,
)


def factor_definition(
    factor_id: str = "factor.ma20.distance",
    *,
    dependencies: tuple[str, ...] = (),
) -> FactorDefinition:
    return FactorDefinition(
        factor_id=factor_id,
        factor_name="MA20 Distance Contract",
        factor_family="technical.trend",
        financial_hypothesis="Price distance from MA20 describes trend extension.",
        asset_class="multi-asset",
        market="registered-market",
        instrument_scope="registered-instruments",
        research_horizon="daily",
        input_frequency="daily",
        output_frequency="daily",
        formula="close / ma20 - 1",
        formula_version="formula.v1",
        parameter_schema={"window": {"type": "integer", "value": 20}},
        parameter_version="params.v1",
        input_fields=("close", "ma20"),
        source_requirements=("registered-source",),
        point_in_time_required=True,
        lookback_window="20d",
        minimum_history=20,
        normalization_method="none",
        winsorization_method="none",
        missing_value_policy="abstain",
        outlier_policy="flag",
        neutralization_policy="none",
        expected_direction="positive",
        valid_market_regimes=("normal", "trend"),
        invalid_market_regimes=("halted",),
        risk_flags=("extension-risk",),
        known_failure_modes=("gap-regime",),
        validation_status=ValidationStatus.VALIDATED,
        champion_challenger_status=ChampionChallengerStatus.UNASSIGNED,
        approved_by="operator.fixture",
        evidence_refs=("evidence.factor.ma20",),
        correlation_id="corr.v2-r1.fixture",
        effective_at_utc="2026-07-17T00:00:00Z",
        retired_at_utc=None,
        owner="factor-governance",
        dependency_factor_ids=dependencies,
        dependency_data_fields=("close", "ma20"),
        calculation_unit="ratio",
        output_range=("-10", "10"),
        deterministic_test_vectors=(
            {"inputs": {"close": "110", "ma20": "100"}, "expected": "0.1"},
        ),
        reference_implementation_version="reference.v1",
        compute_cost_class="low",
        revision_policy="append-only",
        backfill_policy="explicit-operator-review",
        replacement_factor_id=None,
        lifecycle=FactorLifecycle.DRAFT,
    )


def forecast_target_definition() -> ForecastTargetDefinition:
    return ForecastTargetDefinition(
        target_id="target.return.1d",
        target_version="target.v1",
        asset_class="multi-asset",
        market="registered-market",
        instrument_scope="registered-instruments",
        decision_time_basis="snapshot-close",
        forecast_horizon="1d",
        maturity_rule="next-session-close",
        target_type=ForecastTargetType.RETURN,
        formula="matured_close / decision_close - 1",
        basis=TargetBasis.ABSOLUTE,
        objective="direction-and-magnitude",
        cost_treatment="exclude-research-only",
        slippage_treatment="exclude-research-only",
        capacity_treatment="record-not-score",
        label_availability_rule="maturity-plus-source-finality",
        benchmark_policy="none",
        neutralization_policy="none",
        missing_behavior="abstain",
        invalid_behavior="reject",
        censored_behavior="flag",
        abstention_behavior="retain-audit-record",
        evaluation_metrics=("mae", "rank-ic"),
        minimum_sample=100,
        evidence_refs=("evidence.target.return.1d",),
        owner="target-governance",
        effective_at_utc="2026-07-17T00:00:00Z",
    )


def state_sync_anchor(**overrides):
    values = {
        "event_id": "event.market.snapshot.001",
        "instrument_id": "instrument.fixture",
        "event_time_utc": "2026-07-17T01:00:00Z",
        "source_time_utc": "2026-07-17T01:00:01Z",
        "ingest_time_utc": "2026-07-17T01:00:02Z",
        "processing_time_utc": "2026-07-17T01:00:03Z",
        "snapshot_time_utc": "2026-07-17T01:00:04Z",
        "ttl_seconds": 60,
        "baseline_id": "baseline.fixture.001",
        "source_sequence": 1,
        "factor_version": "factor-set.v1",
        "data_quality_status": "registered-valid",
        "data_latency_ms": 2000,
        "registered_artifact_id": "artifact.fixture.snapshot.001",
        "payload": {"close": "100.00", "volume": "12345"},
    }
    values.update(overrides)
    return build_state_sync_anchor(**values)
