"""Readiness-only AI orchestration runtime sidecar."""

from .contract import (
    ALLOWED_INPUTS,
    ALLOWED_OUTPUTS,
    APP_ID,
    CONTRACT_VERSION,
    FORBIDDEN_CAPABILITIES,
    OVERLAP_POLICY,
    POLICY_CONFIG_LINKAGE,
    READINESS_MODE,
    REQUIRED_CONTRACT_FIELDS,
    REQUIRED_FALSE_FLAGS,
    REQUIRED_POLICY_IDENTIFIERS,
    REQUIRED_TRUE_FLAGS,
    RUNTIME_READINESS_STATES,
    STAGE_ID,
    build_runtime_readiness_boundary_contract,
    validate_runtime_readiness_boundary_contract,
)
from .role_contracts import (
    REQUIRED_MANIFEST_FIELDS,
    REQUIRED_OUTPUT_OWNERSHIP_FIELDS,
    REQUIRED_ROLE_FIELDS,
    ROLE_AUTHORITIES,
    ROLE_CONTRACT_VERSION,
    ROLE_DEFINITIONS,
    ROLE_KINDS,
    ROLE_MANIFEST_VERSION,
    ROLE_POLICY_IDENTIFIERS,
    ROLE_STATUSES,
    STAGE_ID as ROLE_CONTRACT_STAGE_ID,
    TERMINAL_OPERATOR_ROLE_ID,
    RoleContractViolation,
    build_machine_readable_role_contract_manifest,
    validate_machine_readable_role_contract_manifest,
)

__all__ = [
    "ALLOWED_INPUTS",
    "ALLOWED_OUTPUTS",
    "APP_ID",
    "CONTRACT_VERSION",
    "FORBIDDEN_CAPABILITIES",
    "OVERLAP_POLICY",
    "POLICY_CONFIG_LINKAGE",
    "READINESS_MODE",
    "REQUIRED_CONTRACT_FIELDS",
    "REQUIRED_FALSE_FLAGS",
    "REQUIRED_MANIFEST_FIELDS",
    "REQUIRED_OUTPUT_OWNERSHIP_FIELDS",
    "REQUIRED_POLICY_IDENTIFIERS",
    "REQUIRED_ROLE_FIELDS",
    "REQUIRED_TRUE_FLAGS",
    "ROLE_AUTHORITIES",
    "ROLE_CONTRACT_STAGE_ID",
    "ROLE_CONTRACT_VERSION",
    "ROLE_DEFINITIONS",
    "ROLE_KINDS",
    "ROLE_MANIFEST_VERSION",
    "ROLE_POLICY_IDENTIFIERS",
    "ROLE_STATUSES",
    "RUNTIME_READINESS_STATES",
    "STAGE_ID",
    "TERMINAL_OPERATOR_ROLE_ID",
    "RoleContractViolation",
    "build_machine_readable_role_contract_manifest",
    "build_runtime_readiness_boundary_contract",
    "validate_machine_readable_role_contract_manifest",
    "validate_runtime_readiness_boundary_contract",
]